// This is an autogenerated file from Firebase Studio.
// DO NOT EDIT.
import { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration
// IMPORTANT: Replace the placeholder values below with your actual Firebase project credentials.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_PROJECT_ID.firebaseapp.com",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_PROJECT_ID.appspot.com",
  messagingSenderId: "YOUR_SENDER_ID",
  appId: "YOUR_APP_ID"
};
