// This is an autogenerated file from Firebase Studio.
// DO NOT EDIT.

import { initializeApp, getApp, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { firebaseConfig } from './config';

// A map of Firebase instances, keyed by their config.
// This is to avoid re-initializing the same app over and over.
const INSTANCES = new Map<string, { app: FirebaseApp; auth: Auth; firestore: Firestore }>();

/**
 * Initializes a Firebase app if it hasn't been initialized yet.
 * @returns An object containing the Firebase app, auth, and firestore instances.
 */
export function initializeFirebase() {
  const key = JSON.stringify(firebaseConfig);
  if (INSTANCES.has(key)) {
    return INSTANCES.get(key)!;
  }

  try {
    const app = getApp();
    const auth = getAuth(app);
    const firestore = getFirestore(app);
    const instances = { app, auth, firestore };
    INSTANCES.set(key, instances);
    return instances;
  } catch (e) {
    const app = initializeApp(firebaseConfig);
    const auth = getAuth(app);
    const firestore = getFirestore(app);
    const instances = { app, auth, firestore };
    INSTANCES.set(key, instances);
    return instances;
  }
}
